---
title: 'BMI-brain plotting'
author: "Jon Thompson, Pers lab"
date: "`r Sys.time()`"
output:
  html_notebook:
    df_print: paged
    number_sections: yes
    toc: yes
    toc_depth: 3
    toc_float: yes
  html_document:
    df_print: paged
    number_sections: yes
    toc: yes
    toc_depth: 3
    toc_float: yes
---
# setup

```{r}
# for network plots, load WGCNA session image. Do this before sourcing functions since the session image functions will be dated
#load("/projects/jonatan/applied/18-mousebrain_7/RObjects/Neurons_sub_ClusterName_7.2_run1_final_session_image.RData.gz")

```

## source
```{r}
source(file="/projects/jonatan/tools/functions-src/utility_functions.R")
source(file="/projects/jonatan/tools/functions-src/functions_sc.R")
```

## packages

```{r}
if (F) for (pkg in c("gplots","kernlab","mclust","modeltools","prabclus","purrr","robustbase","scales","stringi","stringr","tidyr","trimcluster")) install.packages(pkg)
```

```{r}

#ipak(c("WGCNA", "Matrix","dplyr", "parallel", "reshape", "reshape2", "ggplot2", "plotly", "ComplexHeatmap"))
#ipak(c("ComplexHeatmap", "igraph", "WGCNA", "RColorBrewer"))
#ipak(c("corrr", "ggraph", "here", "tidygraph", "tidyverse"))

```

## options

```{r}
options(stringsAsFactors = F, use= "pairwise.complete.obs", warn=1)
```

## constants

```{r}

ncelltypes =11
p.val.threshold = 5e-2

dirOut <- "/projects/jonatan/applied/18-mousebrain_7/"
# Set paths
dirTables = paste0(dirOut, "tables/")
dirLog <- paste0(dirOut, "log/")
dirRObjects <- paste0(dirOut, "RObjects/")
dirPlots <- paste0(dirOut, "plots/")
dirScratch = "/scratch/jonatan/"

# Make directories
for (direc in list(dirLog, dirRObjects, dirPlots)) {
  if (!file.exists(direc)) {
    dir.create(direc)
  }
}

flag_date = substr(gsub("-","",as.character(Sys.Date())),3,1000)
prefixOut <- paste0("mb_7.2_", flag_date)
```


#### Module network plots
Use code from Gandal et al
https://github.com/mgandal/Shared-molecular-neuropathology-across-major-psychiatric-disorders-parallels-polygenic-overlap/blob/master/code/03_networkMegaAnalysis/3f_network_visualization.R

network plot function

see original verbose version at the end of the script

```{r}

module = "lavenderblush"
#module = "lightpink3"
celltype = names(list_mods_uniq)[sapply(list_mods_uniq,
                                           function(mods_uniq){
                                             module%in%mods_uniq
                                           })]
#celltypes=c("DEGLU4",  "DEGLU5",  "DEINH3",  "MEGLU1",  "MEGLU10", "MEGLU11", "MEINH2",  "TEGLU4",  "TEGLU17", "TEGLU23", "TEINH12")
moduleColors = list_colors_meta[[celltype]]
datExpr = list_datExpr_meta[[celltype]]
MEs = list_MEs_meta[[celltype]]
#modColors = data.frame(color= moduleColors,row.names = colnames(datExpr))
```

map from ensembl to symbol

```{r}
df_mapping <- load_obj("/projects/jonatan/tools/gene_set_enrichment/mapping_mmusculus.csv")
colnames(datExpr) <- gene_map(dataIn = colnames(datExpr), df_mapping = df_mapping, from="ensembl",to="symbol", na.rm = F) 
names(moduleColors) <- gene_map(dataIn = names(moduleColors), df_mapping = df_mapping, from="ensembl",to="symbol", na.rm = F) 
```

```{r}
sum(is.na(colnames(datExpr)))
sum(is.na(names(moduleColors)))
```

Compute kMEs

```{r}

kMEs = signedKME(datExpr, MEs, outputColumnName="")
#kMEs <- list_kMs_meta
colnames(kMEs)=colnames(MEs) # for som reason signedKME cuts first part 
maxsize = min(40, sum(moduleColors==module)) #plot top n hub genes in each module
  
```


save arguments to file

```{r}
saveMeta(savefnc=write.csv, x= datExpr, file=gzfile(paste0(dirFiles, prefixOut,"_", module, "_", celltype, "_datExprScaled.csv.gz")), row.names = T, quote=F)
saveMeta(savefnc=write.csv, x= kMEs, file=gzfile(paste0(dirFiles, prefixOut,"_", module, "_", celltype, "_kMEs.csv.gz")), quote=F,row.names=T)
saveMeta(savefnc=saveRDS, object=moduleColors , file=paste0(dirTables, "networkplot_args/", prefixOut, "_", module,  "_", celltype,"_moduleColors.RDS.gz"), compress="gzip")
```

```{r}
colnames(datExpr) <- gsub("X|\\.","", colnames(datExpr))
rownames(datExpr)  <- gsub('"', '', rownames(datExpr))

colnames(kMEs) <- gsub("X|\\.","", colnames(kMEs))
rownames(kMEs)  <- gsub('"', '', rownames(kMEs))
```

## 201903 version

```{r, fig.width=12,fig.height=12}
require("igraph")
require("WGCNA")

plotnetwork <- function(module, 
                        datExpr, 
                        kMEs, 
                        maxsize=40, 
                        path=NULL,
                        returnAdjMat = F) {
  #' @argument module: the gene module to plot, character of length 1
  #' @argument moduleColors: vector of module labels with gene names, character
  #' @argument datExpr: cell * gene matrix, gene colnames must match moduleColors names
  #' @argument kMEs: output of WGCNA::signedKME, numeric data.frame with gene rownames matching moduleColors names and datExpr colnames
  #' @argument maxsize: max number of genes to display, integer, defaults to 40
  #' @argument path: path to which to write plot as pdf. Default is to send plot to default device.
  #' @argument returnAdjMat: return adjacency matrix? Boolean, defaults to F
  #' @value NULL
  #' @usage plotnetwork(module="lavenderblush", moduleColors = moduleColors, datExpr = datExpr, kMEs=kMEs, path=paste0(dirPlots, prefixOut, "_", module, "_networkplot.pdf"), returnAdjMat = F)

  # Get the idx and kME values of top module genes ordered by decreasing kME
  gene_idx <- order(kMEs[,module], decreasing = T)[1:maxsize]
  names(gene_idx) <- rownames(kMEs)[gene_idx]
  mod_kMEs = kMEs[gene_idx, module]

  # make non-negative correlation matrix -> adjacency matrix
  if (class(all.equal(colnames(datExpr), rownames(kMEs)))=="character") datExpr<-datExpr[,order(rownames(kMEs))]
  adjMat = cor(datExpr[,gene_idx])
  
  # only keep positive correlations
  adjMat[adjMat<0] <- 0

  # make graph
  g1 <- graph.adjacency(as.matrix(adjMat),
                        mode="undirected",
                        weighted=T,
                        diag=FALSE)
  edgecolors = numbers2colors(E(g1)$weight, colors = redWhiteGreen(100, gamma=4), signed=T, centered=T, lim=c(-1,1))
  
  #plot
  if (!is.null(path)) pdf(path,useDingbats = F, width=12,height=12)
  plot.igraph(g1, 
              vertex.label = names(gene_idx),
              vertex.label.dist=0, 
              edge.width=0.25,
              vertex.size=mod_kMEs*30, 
              vertex.frame.color="black",
              vertex.label.color="black",
              vertex.color = "white",#modColors[[1]][gene_idx],
              vertex.label.cex=1,
              layout=layout.fruchterman.reingold(g1),
              edge.color="green")
  if(!is.null(path)) invisible(dev.off())
  
  if (returnAdjMat) return(adjMat)
  
}
  
```


call the function

```{r}

dirFiles = "/projects/jonatan/applied/18-mousebrain_7/tables/networkplot_args/"
dirPlots ="/projects/jonatan/applied/18-mousebrain_7/plots/"
prefixOut ="mb_7.2_190408"

celltype <- "MEINH2" 
#celltype <- "TEGLU23"

module <-  "lavenderblush" 
#module <- "lightpink3"

moduleColors = readRDS(paste0(dirFiles, prefixOut,"_", module, "_", celltype, "_moduleColors.RDS.gz"))
datExpr = read.csv(paste0(dirFiles, prefixOut,"_", module, "_", celltype, "_datExprScaled.csv.gz"), quote="", stringsAsFactors = F, row.names = 1)
kMEs =read.csv(paste0(dirFiles, prefixOut,"_", module, "_", celltype, "_kMEs.csv.gz"), quote="", stringsAsFactors = F, row.names=1)


plotnetwork(module=module, 
            moduleColors = moduleColors, 
            datExpr = datExpr, 
            maxsize = 40,
            kMEs = kMEs,
            path=paste0(dirPlots, prefixOut, "_", module, "_networkplot.pdf"),
            returnAdjMat = F)
```

### 20190424 version

WGCNA workflow

Module preprocessor 

```{r}
require(WGCNA)
networkplotPrep <- function(dirWGCNARObjects,
                       prefix_data, 
                       prefix_run,
                       nGenesPlot= 40,
                       module) {
#' @argument dirWGCNAObjects: path to WGCNA ROBjects subdirectory
#' @argument prefix_data: data prefix, character
#' @argument prefix_run: run prefix, character
#' @argument nGenesPlot: number of genes to plot, defaults to 40, integer
#' @argument module: the gene module to plot, character

#' @value list with two components:
#    vec_kMs, vector of module kMs, amed numeric vector
#    mat_adj, gene-gene adjacency matrix, matrix
#' @usage list_networkPlotArgs <- networkplotPrep(dirWGCNARObjects = "~/WGCNAanalysis/RObjects/", prefix_data="sc", prefix_run="1", module="yellowgreen")

  # Load WGCNA run image
  path_image <- dir(path=dirWGCNARObjects, pattern=paste0(prefix_data, "_", prefix_run, "_final_session_image.RData.gz"), full.names = T)
  newEnv <- new.env()
  load(file=path_image, envir=newEnv)
  
  # get vector of module labels with gene names, character
  df_geneModule <- newEnv$df_meta_module_genes
  colname_kMs <- paste0("p", newEnv$params_run$fuzzyModMembership) #grep("^pk",colnames(df_geneModule),value = T)
  
  # Get ordered, named vec_kMEs
  idx_modGenes <- which(df_geneModule$module==module)
  idx_modGenesOrder <- idx_modGenes[order(df_geneModule[[colname_kMs]][idx_modGenes], decreasing = T)]
  vec_kMs <- df_geneModule[[colname_kMs]][idx_modGenesOrder]
  
  colGenes <- if (newEnv$params_run$map_genes_to_ensembl) "ensembl" else "hgnc"
  names(vec_kMs) <- df_geneModule[[colGenes]][idx_modGenesOrder]
  vec_kMs <- vec_kMs[1:min(length(vec_kMs), nGenesPlot)]

  # Get datExpr 
  cellClust <- unique(df_geneModule$cell_cluster[df_geneModule$module==module])
  datExpr <- newEnv$list_datExpr_meta[[cellClust]]
  
  # compute correlation adjacency matrix
  mat_adj = cor(datExpr[,names(vec_kMs)])
  
  # only keep positive correlations
  mat_adj[mat_adj<0] <- 0
  
  return(list("vec_kMs"=vec_kMs, "mat_adj"=mat_adj))
}
```


network plot function

```{r}
require(igraph)
require(WGCNA)

plotGeneNetwork <- function(vec_kMs, mat_adj) {
#' @argument vec_kMs: vector of module kMs, as returned by networkplotPrep, named numeric vector
#' @argument mat_adj: gene-gene adjacency matrix, as returned by networkplotPrep, matrix

#' @value returns NULL invisible
#' @usage 
#'  pdf(paste0(dirPlots, prefixOut, "_", module, "_networkplot.pdf"),useDingbats = F, width=12,height=12)
#'  plotGeneNetwork(vec_kMs=list_networkPlotArgs$vec_kMs, mat_adj=list_networkPlotArgs$mat_adj)
#'  dev.off()

  g1 <- graph.adjacency(as.matrix(mat_adj),
                        mode="undirected",
                        weighted=T,
                        diag=FALSE)
  edgecolors = numbers2colors(E(g1)$weight, colors = redWhiteGreen(100, gamma=4), signed=T, centered=T, lim=c(-1,1))
  
  plot.igraph(g1, 
              vertex.label = names(vec_kMs),
              vertex.label.dist=0, 
              edge.width=0.25,
              vertex.size=vec_kMs*30, 
              vertex.frame.color="black",
              vertex.label.color="black",
              vertex.color = "white",#modColors[[1]][gene_idx],
              vertex.label.cex=1,
              layout=layout.fruchterman.reingold(g1),
              edge.color="green")
  #if(!is.null(path)) invisible(dev.off())
}
```

```{r}
dir_plots=  "/projects/jonatan/applied/18-mousebrain_7/plots/"
module="lavenderblush"
prefix_run="run1"
prefix_data="Neurons_sub_ClusterName_7.2"
dirWGCNARObjects ="/projects/jonatan/applied/18-mousebrain_7/RObjects/"

list_networkPlotArgs <- networkplotPrep(dirWGCNARObjects =dirWGCNARObjects, 
                                        prefix_data=prefix_data, 
                                        prefix_run = prefix_run, 
                                        nGenesPlot = 50,
                                        module=module)

pdf(paste0(dir_plots, prefix_data, "_", prefix_run, "_", module, "_networkplot_test.pdf"),useDingbats = F, width=12,height=12)
plotGeneNetwork(vec_kMs=list_networkPlotArgs$vec_kMs, 
                mat_adj=list_networkPlotArgs$mat_adj)
dev.off()
```




=========
leftovers
=========

```{r}
df.corrr.long <- df.corrr %>%
  shave() %>% # # Convert the upper or lower triangle of a correlation data frame (cor_df) to missing values.
  stretch(na.rm = TRUE) # convert to long format. na.rm = TRUE: matrix diagonal (self-correlation) have NA values and will be dropped.
```


```{r}
modules = c("lavenderblush", "lightpink3")
```

```{r}
for (module in modules) {
  
  celltype = names(list_mods_uniq)[sapply(list_mods_uniq, 
                                             function(mods_uniq){
                                               module%in%mods_uniq
                                             })]
  
  
  moduleColors = list_colors_meta[[celltype]]
  datExpr = list_datExpr_meta[[celltype]]
  MEs = list_MEs_meta[[celltype]]

  modColors = data.frame(color= moduleColors,row.names = colnames(datExpr))
  cons_kme = signedKME(datExpr, MEs, outputColumnName="")
  colnames(cons_kme)=colnames(MEs) # for som reason signedKME cuts first part 
  maxsize = min(40, sum(modColors==module)) #plot top n hub genes in each module
  
  gene_idx = order(cons_kme[which(moduleColors==module),1], decreasing = T)[1:maxsize]

  gene_idx = c(gene_idx, order(cons_kme[,module], decreasing = T)[1:maxsize])
  
  hubGenes = character()
  hubGenes.kme = numeric()
  
  modgenes = colnames(datExpr)[which((modColors) == module)]
  kmes = cons_kme[modgenes, module]
  top_hubs = modgenes[order(kmes, decreasing=T)[1:maxsize]]
  top_hubs.kme = kmes[order(kmes, decreasing=T)[1:maxsize]]
  hubGenes = c(hubGenes,top_hubs)
  hubGenes.kme = c(hubGenes.kme, top_hubs.kme)

  gene_idx = match(hubGenes,colnames(datExpr))
  keepgenes = rownames(cons_kme)[gene_idx]
  
  if (FALSE) {
    adjMat = cor(datExpr)
    adjMat = adjMat[gene_idx,gene_idx]
    #topcors=0.65^9
  
    adjMat[adjMat< 0]=0
    #geneSymbols = datProbes$external_gene_id[match(keepgenes, datProbes$ensembl_gene_id)]
    geneSymbols = df_NWA[["hgnc"]][match(keepgenes,df_NWA[["ensembl"]])]
    g1 <- graph.adjacency(as.matrix(adjMat),mode="undirected",weighted=T,diag=FALSE)
    # mds = cmdscale(dist(t(adjMat)), eig = T)
    # layoutFR = mds$points
    edgecolors = numbers2colors(E(g1)$weight, colors = redWhiteGreen(100, gamma=4), signed=T, centered=T, lim=c(-1,1))
    
    
    pdf(paste0(dirPlots, prefixOut, "_", module, "_networkplot.pdf"),useDingbats = F, width=12,height=12)
    
    plot.igraph(g1, 
                vertex.label = geneSymbols,
                vertex.label.dist=0, 
                edge.width=0.25,
                vertex.size=hubGenes.kme*30, 
                vertex.frame.color="black",
                vertex.label.color="black",
                vertex.color = "white",#modColors[[1]][gene_idx],
                vertex.label.cex=1,
                layout=layout.fruchterman.reingold(g1),
                edge.color="green")
    dev.off()
  }
  
  #### NEW
  datExprSub <- datExpr[,gene_idx] 
  colnames(datExprSub) <- df_NWA[["hgnc"]][match(colnames(datExprSub),df_NWA[["ensembl"]])]
  df.corrr <- datExprSub %>% correlate(use = "pairwise.complete.obs", method="pearson")

  df.corrr %>% shave() %>% stretch(na.rm=T) -> df.corrr.long
  
  gr <- tbl_graph(nodes=data.frame(genes = unique(df.corrr.long$x)),#df.module_metadata, 
                  edges=df.corrr.long %>% filter(r>=0), directed=FALSE)
  

}
```
